config-version: 2.0.0
groups:
  - "965325092"
join_msg: "玩家%player_name%加入了服务器"
quit_msg: "玩家%player_name%离开了服务器"
group_chat_msg: "<%player_name%>: {MSG}"
game_chat_msg: "&7[QQ群] {CARD}: {MSG}"
future:
  supported_ChatImage: true
  qq2mc_message_truncation:
    enabled: true
    max_length: 30
    truncation_notice: "[原消息过长已自动截断]"
  mc2qq_message_truncation:
    enabled: true
    max_length: 30
    truncation_notice: "[原消息过长已自动截断]"
debug: false
bstats: true