name: XavierChatSync
version: '1.0-SNAPSHOT'
main: xaviermc.top.xavierChatSync.XavierChatSync
api-version: '1.12'
depend: [XinxinBotApi,PlaceholderAPI]
authors: [CerealAxis]
website: xaviermc.top
commands:
  xavierchatsync:
    permission: xavierchatsync.admin
    aliases: [xcs]