name: XavierChatSync
version: ${version}
main: xaviermc.top.xavierChatSync.XavierChatSync
depend: [XinxinBotApi,PlaceholderAPI]
authors: [CerealAxis]
website: xaviermc.top
commands:
  xavierchatsync:
    permission: xavierchatsync.admin
    aliases: [xcs]