name: "Dev Build"

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Execute Gradle build
        run: ./gradlew shadowJar

      - uses: actions/upload-artifact@v4
        with:
          name: Package JAR
          path: build/libs